version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: '[platform]'

  - package-ecosystem: swift
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: '[platform]'
