#!/usr/bin/env bash

## Build script

ROOT_DIR="$(dirname "$(tmp=${0%/*}; echo "$PWD${tmp##\.}")")"
APP_NAME=DiffFormatter

if [[ -z $HOMEBREW_PREFIX ]] && which fastlane >/dev/null; then
  bundle exec fastlane build
else
  xcodebuild clean install -project "$ROOT_DIR/$APP_NAME.xcodeproj" -target $APP_NAME
fi

