#!/usr/bin/env bash

## Install script

ROOT_DIR="$(dirname "$(tmp=${0%/*}; echo "$PWD${tmp##\.}")")"

APP_NAME='DiffFormatter'
CONFIG_PATH="$HOME/.diff_formatter"
CONFIG_MESSAGE='Add/overwrite default config in home directory? (y/n) '

xcodebuild clean install -project "$ROOT_DIR/$APP_NAME.xcodeproj" -target $APP_NAME

# Exit early if install called from within another script

if [[ "$0" != "$BASH_SOURCE" ]]; then
  exit 0
fi

read -p "$CONFIG_MESSAGE" -n 1 -t 5 -r CONFIRMATION < /dev/tty

if [[ ! $CONFIRMATION =~ ^[Yy]$ ]]; then
  echo -e "\n\nInstall completed without adding default config\n"
else
  echo -e "\n\nInstalling default config to: $CONFIG_PATH\n"
  cp "$ROOT_DIR/.diff_formatter_template" $CONFIG_PATH
fi
