#!/usr/bin/env bash

# Call this script with a warning message argument to precede the confirmation prompt
read -p "$@ Are you sure? [Y/n] " -n 1 -t 10 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi
