#!/usr/bin/env bash

APP_NAME=DiffFormatter
BUILD_NUMBER_FILE=$(dirname $0)/../Sources/$APP_NAME/App/BuildNumber.swift

echo "let appBuildNumber: Int = $(git rev-list @ --count)" > $BUILD_NUMBER_FILE

